server:
  port: 4321

spring:
  datasource:
    username: root
    password: 71114411
    url: jdbc:mysql://localhost:3306/poseidon-admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true



leon:
  poseidon:
    jwt:
      header: Authorization
      expire: 604800 # 7天，s为单位
      secret: abcdefghabcdefghabcdefghabcdefgh
      issuer: leon-poseidon-security
      token-header: Bearer